server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否注册自身到eureka服务器
    registerWithEureka: false
    # 是否从eureka上获取注册信息
    fetchRegistry: false
    # 服务器url
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

